package com.comp3000.project.cms.common;

public enum EventType {
    CREATION,
    MODIFICATION,
    DELETION,
    COURSE_REGISTRATION,
    WITHDRAWAL,
    FINAL_GRADE_SUBMISSION_ALL,
    FINAL_GRADE_SUBMISSION_SINGLE,
    DELIVERABLE_GRADE_SUBMISSION_ALL,
    DELIVERABLE_GRADE_SUBMISSION_SINGLE
}
